# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title (ru)')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Text (ru)')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivitySlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='upload/activities/slides', verbose_name='Activity Slide')),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='activities.Activity', verbose_name='Activity')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
