# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title (ru)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description (ru)')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Text (ru)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Display')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='upload/slides', verbose_name='Slide')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
